name: flutter_template

packages:
  - src/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  get:
    exec: dart pub get .
  build:
    run: flutter pub run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
    packageFilters:
      dependsOn: build_runner
  watch:
    run: flutter pub run build_runner watch --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
  analyze:
    exec: dart analyze .
  test:
    run: flutter test
    packageFilters:
      dirExists: test
