name: Flutter Build Test

on:
  push:
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Install Melos
      uses: bluefireteam/melos-action@v3

    - name: Install Dependencies
      run: melos get

    - name: Run Flutter Tests
      run: melos test --machine --coverage > tests.output

    - run: melos analyze

  release:
    name: Release
    if: github.ref_name == 'main' || github.ref_name == 'beta' || github.ref_name == 'alpha'
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: npm install semantic-release-pub
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}